spring.application.name=receipt-service
# SQLite
spring.datasource.url=jdbc:sqlite:receipts.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

storage.upload-directory=uploads